# Dataset and dataloader parameters
dataset: 'nuScenes'
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'graphs'

train_set_args: &ds_args
  split: 'train'
  t_h: 2
  t_f: 6
  map_extent: [ -50, 50, -20, 80 ]
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  random_flips: True

val_set_args:
  <<: *ds_args
  split: 'train_val'
  random_flips: False

test_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False

batch_size: 32
num_workers: 0


# Encoder parameters
encoder_type: 'new'
encoder_args:
  hidden_dim: 64
  num_freq_bands: 32
  num_heads: 8
  dropout: 0.1
  attn_layers: 2
  num_gat_layers: 2

# Aggregator parameters
aggregator_type: 'ac_aggregator'
aggregator_args:
  hidden_size: 64
  num_heads: 8
  dropout: 0.1
  num_modes: 10
  op_len: 12
  num_inter_layers: 3
  evaporation_rate: 0.1


# Decoder parameters
decoder_type: 'new'
decoder_args:
  num_modes: 10
  dropout: 0.1
  pred_len: 12
  hidden_dim: 64
  min_scale: 0.0001

# Optimizer parameters
optim_args:
  lr: 0.0005
  T_max: 150
  eta_min: 0.00001


losses: ['min_ade_k', 'LaplaceLoss']
loss_weights: [1, 1]
loss_args:
  - k: 5
  - None: None


tr_metrics: ['min_ade_k','min_ade_k', 'miss_rate_k', 'miss_rate_k', 'LaplaceLoss']
tr_metric_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - None: None

val_metrics: ['min_ade_k','min_ade_k', 'miss_rate_k', 'miss_rate_k', 'LaplaceLoss']
val_metric_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - None: None


log_freq: 100
